using UnityEngine;
using System.Collections.Generic;
#if UNITY_EDITOR
using UnityEditor;
#endif

// A simple marker component used to remember which colliders were generated by the manager.
// This is the most robust way to track them, as it survives scene saves, duplication, and works even without a manager object in the scene.
public class GeneratedMeshColliderMarker : MonoBehaviour { }

public class ColliderManager : MonoBehaviour
{
    // Allows you to run this from the component's context menu in the Inspector
    [ContextMenu("Add Convex Mesh Colliders")]
    public void AddConvexMeshColliders()
    {
        MeshRenderer[] renderers = FindObjectsOfType<MeshRenderer>(true);
        int addedCount = 0;
        int modifiedCount = 0;

        foreach (MeshRenderer renderer in renderers)
        {
            GameObject go = renderer.gameObject;
            
            MeshCollider collider = go.GetComponent<MeshCollider>();
            if (collider == null)
            {
                collider = go.AddComponent<MeshCollider>();
                collider.convex = true;
                
                // Add marker to remember we created this specific collider
                go.AddComponent<GeneratedMeshColliderMarker>();
                addedCount++;
            }
            else if (!collider.convex)
            {
                // We just set it to convex but didn't create it, so we DON'T add the marker here.
                collider.convex = true;
                modifiedCount++;
            }
        }

        Debug.Log($"Added {addedCount} new MeshColliders and set {modifiedCount} existing ones to convex.");
    }

    [ContextMenu("Remove Generated Mesh Colliders")]
    public void RemoveGeneratedColliders()
    {
        GeneratedMeshColliderMarker[] markers = FindObjectsOfType<GeneratedMeshColliderMarker>(true);
        int removedCount = 0;

        foreach (GeneratedMeshColliderMarker marker in markers)
        {
            GameObject go = marker.gameObject;
            MeshCollider collider = go.GetComponent<MeshCollider>();
            
            if (collider != null)
            {
                if (Application.isPlaying)
                {
                    Destroy(collider);
                    Destroy(marker);
                }
                else
                {
                    DestroyImmediate(collider);
                    DestroyImmediate(marker);
                }
                removedCount++;
            }
        }

        Debug.Log($"Removed {removedCount} generated MeshColliders.");
    }

    void Start()
    {
        // Uncomment the line below if you want this to happen automatically when the game starts.
        // NOTE: Doing this at runtime can be performance intensive for large scenes!
        // AddConvexMeshColliders();
    }

#if UNITY_EDITOR
    // Adds a top menu item in the Unity Editor for convenience
    [MenuItem("Tools/Colliders/Add Convex Mesh Colliders to All Renderers")]
    public static void AddCollidersMenu()
    {
        MeshRenderer[] renderers = FindObjectsOfType<MeshRenderer>(true);
        int addedCount = 0;
        int modifiedCount = 0;

        foreach (MeshRenderer renderer in renderers)
        {
            GameObject go = renderer.gameObject;
            
            MeshCollider collider = go.GetComponent<MeshCollider>();
            if (collider == null)
            {
                Undo.AddComponent<MeshCollider>(go);
                collider = go.GetComponent<MeshCollider>();
                //collider.convex = true;
                
                Undo.AddComponent<GeneratedMeshColliderMarker>(go);
                addedCount++;
            }
            else if (!collider.convex)
            {
                Undo.RecordObject(collider, "Set Convex");
                //collider.convex = true;
                modifiedCount++;
            }
        }

        Debug.Log($"[Editor] Added {addedCount} new MeshColliders and set {modifiedCount} existing ones to convex.");
    }

    [MenuItem("Tools/Colliders/Remove Generated Mesh Colliders")]
    public static void RemoveCollidersMenu()
    {
        GeneratedMeshColliderMarker[] markers = FindObjectsOfType<GeneratedMeshColliderMarker>(true);
        int removedCount = 0;

        foreach (GeneratedMeshColliderMarker marker in markers)
        {
            GameObject go = marker.gameObject;
            MeshCollider collider = go.GetComponent<MeshCollider>();
            
            if (collider != null)
            {
                Undo.DestroyObjectImmediate(collider);
                Undo.DestroyObjectImmediate(marker);
                removedCount++;
            }
            else
            {
                // If somehow the collider was manually deleted but the marker remains
                Undo.DestroyObjectImmediate(marker);
            }
        }

        Debug.Log($"[Editor] Removed {removedCount} generated MeshColliders.");
    }
#endif
}
